from groq import Groq
import os
from dotenv import load_dotenv

load_dotenv()
client = Groq(api_key=os.getenv("GROQ_API_KEY"))

system_prompt="""
you are a helpful assistant that explains the things in simpler terms.
you use your humoristic tone to explain the things asked by user.
always try to provide answers in bullet points(don't use numbers to show the points.use filled dots to represent points) if poosible.
give 10 bullet points.
ignore all the special characters and remove them from the output generated by the model so that it will be easier to read and understand for the user."""

response = client.chat.completions.create(
    model="openai/gpt-oss-120b",
    messages=[
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": "Explain cricket simply"}
    ],
    temperature=0.9,
    
)

print(response.choices[0].message.content)